export const COPY = {
  en: {
    kicker: "Schema Workspace",
    title: "Label Schema Center",
    subtitle: "Manage Label Lab JSON schemas as workspace files with archive and restore.",
    includeArchived: "Include archived",
    refresh: "Refresh",
    createNew: "New",
    schemas: "Schemas",
    noSchemas: "No label schemas found.",
    editor: "Editor",
    key: "Key",
    label: "Label",
    description: "Description",
    schema: "JSON Schema",
    saveCreate: "Create",
    saveUpdate: "Update",
    archive: "Archive",
    restore: "Restore",
    purge: "Purge",
    openInLabelLab: "Open In Label Lab",
    archived: "Archived",
    active: "Active",
    readOnly: "Archived schemas are read-only. Restore first to edit.",
    selectHint: "Select a schema from the list, or create a new one.",
    confirmPurge: "Permanently purge this archived schema?",
  },
  zh: {
    kicker: "Schema 工作区",
    title: "标注 Schema 中心",
    subtitle: "以工作区文件方式管理 Label Lab JSON Schema，支持归档与恢复。",
    includeArchived: "包含已归档",
    refresh: "刷新",
    createNew: "新建",
    schemas: "Schema 列表",
    noSchemas: "没有找到标注 Schema。",
    editor: "编辑器",
    key: "键名",
    label: "标题",
    description: "描述",
    schema: "JSON Schema",
    saveCreate: "创建",
    saveUpdate: "更新",
    archive: "归档",
    restore: "恢复",
    purge: "彻底删除",
    openInLabelLab: "在标注实验室中打开",
    archived: "已归档",
    active: "生效中",
    readOnly: "已归档 Schema 为只读，请先恢复后再编辑。",
    selectHint: "请从列表选择 Schema，或创建新的 Schema。",
    confirmPurge: "确认彻底删除该归档 Schema 吗？",
  },
} as const;

export type SchemaCenterCopy = { [Key in keyof (typeof COPY)["en"]]: string };
