export const COPY = {
  en: {
    kicker: "Custom Tool Workspace",
    title: "Tool Center",
    subtitle:
      "CRUD managed custom tools with workspace persistence and instant Agent Studio availability. Built-ins stay read-only.",
    includeArchived: "Include archived",
    includeBuiltin: "Include built-ins",
    includeSourceInList: "Include source in list",
    search: "Search",
    refresh: "Refresh",
    createNew: "New custom tool",
    attachStudio: "Open Agent Studio (Tools)",
    slug: "Slug",
    description: "Description",
    tags: "Tags (comma separated)",
    source: "Python source",
    create: "Create",
    update: "Update",
    archive: "Archive",
    restore: "Restore",
    purge: "Purge",
    noResults: "No tools matched the current filters.",
    readOnlyBuiltin: "Built-in tool (read-only)",
    managedTool: "Managed custom tool",
    archivedBadge: "Archived",
    activeBadge: "Active",
    confirmPurge: "Permanently purge this archived custom tool?",
  },
  zh: {
    kicker: "自定义工具工作区",
    title: "工具中心",
    subtitle: "对受管自定义工具进行 CRUD，持久化到工作区并即时可用于智能体工作台。内置工具保持只读。",
    includeArchived: "包含已归档",
    includeBuiltin: "包含内置工具",
    includeSourceInList: "列表中包含源码",
    search: "搜索",
    refresh: "刷新",
    createNew: "新建自定义工具",
    attachStudio: "打开智能体工作台（Tools）",
    slug: "Slug",
    description: "描述",
    tags: "标签（逗号分隔）",
    source: "Python 源码",
    create: "创建",
    update: "更新",
    archive: "归档",
    restore: "恢复",
    purge: "彻底删除",
    noResults: "当前筛选下没有工具。",
    readOnlyBuiltin: "内置工具（只读）",
    managedTool: "受管自定义工具",
    archivedBadge: "已归档",
    activeBadge: "生效中",
    confirmPurge: "确认彻底删除该归档自定义工具吗？",
  },
} as const;

export type ToolCenterCopy = { [Key in keyof (typeof COPY)["en"]]: string };
