export const COPY = {
  en: {
    kicker: "Template Workspace",
    title: "Prompt Center",
    subtitle:
      "Manage system prompts and persona templates as workspace files, with archive/restore and immediate availability.",
    promptsTab: "System Prompts",
    personasTab: "Persona Prompts",
    chatScenario: "Chat",
    commentScenario: "Comment",
    labelScenario: "Label",
    scenarioLabel: "Scenario",
    includeArchived: "Include archived",
    refresh: "Refresh",
    createNew: "New",
    key: "Key",
    label: "Label (optional)",
    description: "Description (optional)",
    content: "Content",
    saveCreate: "Create",
    saveUpdate: "Update",
    archive: "Archive",
    restore: "Restore",
    purge: "Purge",
    openInAgentStudio: "Open In Agent Studio",
    openInCommentLab: "Open In Comment Lab",
    openInLabelLab: "Open In Label Lab",
    noTemplates: "No templates found for current filter.",
    activeList: "Templates",
    editor: "Editor",
    archivedBadge: "Archived",
    activeBadge: "Active",
    saveDisabledArchived: "Archived templates are read-only. Restore first to edit.",
    confirmPurge: "Permanently purge this archived template?",
    selectHint: "Select a template from the list, or create a new one.",
  },
  zh: {
    kicker: "模板工作区",
    title: "提示词中心",
    subtitle: "将 System Prompt 与 Persona 模板作为工作区文件管理，支持归档恢复并即时生效。",
    promptsTab: "System Prompt",
    personasTab: "Persona Prompt",
    chatScenario: "Chat",
    commentScenario: "Comment",
    labelScenario: "Label",
    scenarioLabel: "场景",
    includeArchived: "包含已归档",
    refresh: "刷新",
    createNew: "新建",
    key: "键名",
    label: "标题（可选）",
    description: "描述（可选）",
    content: "内容",
    saveCreate: "创建",
    saveUpdate: "更新",
    archive: "归档",
    restore: "恢复",
    purge: "彻底删除",
    openInAgentStudio: "在智能体工作台中打开",
    openInCommentLab: "在评论实验室中打开",
    openInLabelLab: "在标注实验室中打开",
    noTemplates: "当前筛选下没有模板。",
    activeList: "模板列表",
    editor: "编辑器",
    archivedBadge: "已归档",
    activeBadge: "生效中",
    saveDisabledArchived: "已归档模板为只读，请先恢复后再编辑。",
    confirmPurge: "确认彻底删除该归档模板吗？",
    selectHint: "请先从左侧选择模板，或创建新模板。",
  },
} as const;

export type PromptCenterCopy = { [Key in keyof (typeof COPY)["en"]]: string };
