import type { TestRunType } from "./api";
import type { Locale } from "@/shared/i18n";

const COPY = {
  en: {
    kicker: "Evaluation Workspace",
    title: "Test Center",
    intro: "Start by evaluating agent behavior. Platform health checks and native-runtime qualification are kept in a separate operations area below.",
    behaviorKicker: "Product Behavior",
    behaviorTitle: "Improve Agent Behavior",
    behaviorIntro: "Run a controlled chat-memory evaluation, inspect the evidence behind each result, then refine the prompt or persona from what the agent actually did.",
    behaviorLaunchTitle: "Run a Behavior Evaluation",
    behaviorLaunchIntro: "This measures agent behavior. It is not a platform health check or a runtime qualification result.",
    experimentDecisionTitle: "Compare and Decide",
    experimentDecisionIntro: "Compare verified content-addressed inputs and behavior signals, then record what this candidate means for the next iteration.",
    baselineEvaluation: "Baseline evaluation",
    candidateEvaluation: "Candidate evaluation",
    preferredBaseline: "Preferred baseline",
    noComparisonBaseline: "Choose another verified run to compare, or promote this passing run to establish the first baseline.",
    verifiedProvenance: "Verified content-addressed inputs",
    legacyProvenanceMissing: "This historical run predates content-addressed input snapshots. It remains readable, but cannot be trusted for comparison or decisions.",
    sameConfiguration: "Same effective configuration",
    differentConfiguration: "Configuration changed",
    configurationChanges: "Configuration changes",
    noConfigurationChanges: "No effective input changes were detected.",
    baselineValue: "Baseline",
    candidateValue: "Candidate",
    metricChanges: "Behavior signal deltas",
    exactPromptDiff: "Exact prompt snapshots",
    exactPersonaDiff: "Exact persona snapshots",
    modelIdentity: "Model identity",
    promptIdentity: "Prompt identity",
    personaIdentity: "Persona identity",
    evaluationIdentity: "Evaluation identity",
    evidenceIdentity: "Output evidence identity",
    capturedPromptSnapshot: "Captured prompt used by this run",
    capturedPersonaSnapshot: "Captured persona used by this run",
    currentDecision: "Current decision",
    noDecision: "No decision recorded",
    decisionNote: "Decision note",
    decisionNotePlaceholder: "Why should we keep, promote, or reject this candidate?",
    keepDecision: "Keep for reference",
    promoteDecision: "Promote as baseline",
    rejectDecision: "Reject candidate",
    keepDecisionHelp: "Retain the evidence without changing the preferred baseline.",
    promoteDecisionHelp: "Make this complete deterministic pass the default comparison baseline.",
    rejectDecisionHelp: "Mark this configuration unsuitable for further use.",
    decisionRecorded: "Evaluation decision recorded.",
    decisionNeedsProvenance: "This run has no verified content-addressed provenance and cannot receive a decision.",
    decisionKeep: "Kept for reference",
    decisionPromote: "Promoted baseline",
    decisionReject: "Rejected",
    operationsTitle: "Platform Diagnostics and Runtime Qualification",
    operationsIntro: "Use these runs to diagnose API and stack health, or to gather native-runtime qualification evidence. A passing operational check does not score agent behavior.",
    operationsLaunchTitle: "Run an Operational Check",
    operationsLaunchIntro: "These checks verify platform behavior and runtime readiness rather than prompt, persona, or memory quality.",
    createRunTitle: "Create Test Run",
    runType: "Run type",
    chatMemoryEvaluationRun: "Chat-memory behavior evaluation",
    adeApiE2eCheckRun: "ADE API end-to-end check",
    adeMvpSmokeCheckRun: "ADE MVP smoke check",
    nativeRuntimeQualificationRun: "Native runtime qualification",
    model: "Model",
    prompt: "Prompt",
    persona: "Persona",
    embedding: "Embedding",
    fixture: "Fixture",
    rounds: "Rounds",
    timeoutSeconds: "Timeout (seconds)",
    retryCount: "Retry Count (fixed at 0 for evidence integrity)",
    judgeEnabled: "Advisory LLM judge",
    conversationModel: "Conversation deployment",
    reviewerModel: "Reviewer deployment",
    retrieverModel: "Retriever deployment",
    diagnosticCases: "Focused diagnostic cases",
    diagnosticCasesHelp: "Selected cases run once without llama compatibility and are never promotion eligible.",
    llamaCompatibility: "Run nonblocking llama-server compatibility round",
    nativeRuntimeRequirement: "Runs through the opt-in ADE-native API and worker. Complete production-path rounds may generate a reviewed promotion proposal; they never promote automatically.",
    nativeRuntimeDeploymentsUnavailable: "Required conversation, reviewer, and retriever deployment metadata is not currently available. Other Test Center runs remain usable.",
    submitting: "Submitting...",
    createRun: "Create Run",
    refreshRuns: "Refresh Runs",
    evaluationRunsTitle: "Chat-Memory Evaluations",
    evaluationRunsIntro: "Compare agent behavior by setup, then inspect the evidence behind every score.",
    refreshEvaluations: "Refresh Evaluations",
    noEvaluations: "No chat-memory evaluations are available yet.",
    evaluationRun: "Evaluation run",
    evaluationSetup: "Setup",
    evaluationStatus: "Status",
    evaluationSignals: "Behavior signals",
    evaluationDetailsTitle: "Evaluation Detail",
    evaluationPreparing: "Evidence will appear when the evaluation is ready.",
    loadingEvaluation: "Loading evaluation evidence...",
    ready: "Ready",
    pending: "Pending",
    selected: "Selected",
    inspectEvaluation: "Inspect",
    scorecard: "Scorecard",
    behaviorSignals: "Behavior Signals",
    passRate: "Pass rate",
    passedRounds: "Passed rounds",
    facts: "Facts",
    memory: "Memory",
    disclosure: "Disclosure hits",
    tools: "Memory tools / all tools",
    cleanup: "Cleanup",
    latency: "Latency",
    errors: "Errors",
    rerunSetup: "Rerun This Setup",
    rerunPrepared: "Evaluation setup loaded. Review it, then create a run when ready.",
    openPrompt: "Open Prompt",
    openPersona: "Open Persona",
    roundEvidence: "Round Evidence",
    noRoundEvidence: "No completed rounds are available yet.",
    round: "Round",
    passed: "Passed",
    failed: "Failed",
    failureReasons: "Deterministic Failure Reasons",
    forbiddenHitsFailure: "Forbidden self-disclosure detected",
    memoryUnchangedFailure: "Human memory did not change",
    missingFactsFailure: "Missing expected facts",
    expectedFactsFailure: "Expected-fact check failed",
    deterministicFailureFallback: "One or more deterministic checks failed. Open assessment details below.",
    agentId: "Agent ID",
    archived: "Archived",
    purged: "Purged",
    finalMemoryLayers: "Final Memory Layers",
    noMemoryLayers: "No final memory layers were recorded.",
    memoryLimit: "Limit",
    emptyMemory: "(empty)",
    initialHumanMemory: "Initial Human Memory",
    finalHumanMemory: "Final Human Memory",
    assessmentDetails: "Assessment Details",
    deterministicScore: "Deterministic Score",
    judge: "Advisory Judge",
    turnEvidence: "Turn-by-Turn Evidence",
    turn: "Turn",
    userInput: "User Input",
    assistantReplies: "Assistant Replies",
    noAssistantReply: "No assistant reply recorded.",
    humanMemoryBefore: "Human Memory Before",
    humanMemoryAfter: "Human Memory After",
    memoryChanged: "Memory Changed",
    memoryDelta: "Human Memory Delta",
    addedMemoryLines: "Added lines",
    removedMemoryLines: "Removed lines",
    noMemoryDelta: "No line-level memory changes recorded.",
    toolCalls: "All Tool Calls",
    noToolCalls: "No tool calls recorded.",
    memoryToolCalls: "Memory Tool Calls",
    noMemoryToolCalls: "No memory tool calls recorded.",
    rawDiagnostics: "Raw Run Diagnostics",
    rawDiagnosticsIntro: "Artifacts and output tails remain available for lower-level troubleshooting.",
    serverDefault: "Server default",
    runsTitle: "Runs",
    selectRun: "Select run",
    refreshSelectedRun: "Refresh Selected Run",
    cancelRun: "Cancel Run",
    artifactsTitle: "Artifacts",
    refreshArtifacts: "Refresh Artifacts",
    noArtifacts: "No artifacts discovered yet.",
    yes: "yes",
    no: "no",
    open: "Open",
    activeArtifact: "Active artifact",
    noActiveArtifact: "none",
    artifactContentPlaceholder: "Artifact content appears here.",
    outputTail: "Run Output Tail",
    statusTitle: "Status",
    errorTitle: "Error",
    createdRun: "Created run",
    cancelRequested: "Cancel requested for",
    selectRunPlaceholder: "Select run",
    id: "ID",
    type: "Type",
    exists: "Exists",
    action: "Action",
  },
  zh: {
    kicker: "评估工作区",
    title: "测试中心",
    intro: "请先评估智能体行为。平台健康检查和原生运行时资格验证位于下方独立的运维区域。",
    behaviorKicker: "产品行为",
    behaviorTitle: "改善智能体行为",
    behaviorIntro: "运行受控的聊天记忆评估，查看每项结果背后的证据，再根据智能体的实际表现迭代提示词或人设。",
    behaviorLaunchTitle: "运行行为评估",
    behaviorLaunchIntro: "此运行衡量智能体行为，不是平台健康检查，也不是运行时资格验证结果。",
    experimentDecisionTitle: "对比并决策",
    experimentDecisionIntro: "对比已验证、内容寻址的输入与行为信号，然后记录该候选结果对下一轮迭代的意义。",
    baselineEvaluation: "基线评估",
    candidateEvaluation: "候选评估",
    preferredBaseline: "首选基线",
    noComparisonBaseline: "请选择另一个已验证运行进行对比，或将本次通过的运行提升为第一个基线。",
    verifiedProvenance: "已验证的内容寻址输入",
    legacyProvenanceMissing: "该历史运行早于内容寻址输入快照。它仍可查看，但不能用于可信对比或决策。",
    sameConfiguration: "有效配置相同",
    differentConfiguration: "配置已变化",
    configurationChanges: "配置变化",
    noConfigurationChanges: "未检测到有效输入变化。",
    baselineValue: "基线",
    candidateValue: "候选",
    metricChanges: "行为信号变化",
    exactPromptDiff: "精确提示词快照",
    exactPersonaDiff: "精确人设快照",
    modelIdentity: "模型标识",
    promptIdentity: "提示词标识",
    personaIdentity: "人设标识",
    evaluationIdentity: "评估标识",
    evidenceIdentity: "输出证据标识",
    capturedPromptSnapshot: "本次运行使用的提示词快照",
    capturedPersonaSnapshot: "本次运行使用的人设快照",
    currentDecision: "当前决策",
    noDecision: "尚未记录决策",
    decisionNote: "决策说明",
    decisionNotePlaceholder: "为什么要保留、提升或拒绝该候选？",
    keepDecision: "保留作参考",
    promoteDecision: "提升为基线",
    rejectDecision: "拒绝候选",
    keepDecisionHelp: "保留证据，但不改变首选基线。",
    promoteDecisionHelp: "将本次完整确定性通过的运行设为默认对比基线。",
    rejectDecisionHelp: "将该配置标记为不适合继续使用。",
    decisionRecorded: "已记录评估决策。",
    decisionNeedsProvenance: "该运行没有已验证的内容寻址来源，无法记录决策。",
    decisionKeep: "已保留作参考",
    decisionPromote: "已提升为基线",
    decisionReject: "已拒绝",
    operationsTitle: "平台诊断与运行时资格验证",
    operationsIntro: "使用这些运行诊断 API 与技术栈健康状态，或收集原生运行时资格验证证据。通过运维检查并不代表智能体行为得分通过。",
    operationsLaunchTitle: "运行运维检查",
    operationsLaunchIntro: "这些检查验证平台行为与运行时就绪情况，不评估提示词、人设或记忆质量。",
    createRunTitle: "创建测试运行",
    runType: "运行类型",
    chatMemoryEvaluationRun: "聊天记忆行为评估",
    adeApiE2eCheckRun: "ADE API 端到端检查",
    adeMvpSmokeCheckRun: "ADE MVP 烟雾检查",
    nativeRuntimeQualificationRun: "原生运行时资格验证",
    model: "模型",
    prompt: "提示词",
    persona: "人设",
    embedding: "Embedding",
    fixture: "对话样本",
    rounds: "轮数",
    timeoutSeconds: "超时（秒）",
    retryCount: "重试次数（为保证证据完整性固定为 0）",
    judgeEnabled: "启用辅助 LLM 评审",
    conversationModel: "对话模型部署",
    reviewerModel: "记忆评审模型部署",
    retrieverModel: "检索模型部署",
    diagnosticCases: "聚焦诊断用例",
    diagnosticCasesHelp: "选中的用例仅运行一轮，不含 llama 兼容性，且永远不具备晋级资格。",
    llamaCompatibility: "运行不阻断发布的 llama-server 兼容性轮次",
    nativeRuntimeRequirement: "此评估通过可选启用的 ADE 原生 API 与 Worker 运行。完整的生产路径轮次可以生成待审核的晋级提案，但绝不会自动晋级。",
    nativeRuntimeDeploymentsUnavailable: "当前缺少所需的对话、记忆评审或检索部署元数据。测试中心的其他运行仍可继续使用。",
    submitting: "提交中...",
    createRun: "创建运行",
    refreshRuns: "刷新运行列表",
    evaluationRunsTitle: "聊天记忆评估",
    evaluationRunsIntro: "按配置比较智能体行为，并逐轮查看每项评分的证据。",
    refreshEvaluations: "刷新评估",
    noEvaluations: "暂无聊天记忆评估。",
    evaluationRun: "评估运行",
    evaluationSetup: "配置",
    evaluationStatus: "状态",
    evaluationSignals: "行为信号",
    evaluationDetailsTitle: "评估详情",
    evaluationPreparing: "评估就绪后将在此显示证据。",
    loadingEvaluation: "正在加载评估证据...",
    ready: "已就绪",
    pending: "等待中",
    selected: "已选择",
    inspectEvaluation: "查看",
    scorecard: "评分卡",
    behaviorSignals: "行为信号",
    passRate: "通过率",
    passedRounds: "通过轮数",
    facts: "事实",
    memory: "记忆",
    disclosure: "自我暴露命中",
    tools: "记忆工具 / 全部工具",
    cleanup: "清理",
    latency: "耗时",
    errors: "错误",
    rerunSetup: "复用此配置",
    rerunPrepared: "已载入评估配置。请检查后再手动创建运行。",
    openPrompt: "打开提示词",
    openPersona: "打开人设",
    roundEvidence: "逐轮证据",
    noRoundEvidence: "暂无已完成轮次。",
    round: "第",
    passed: "通过",
    failed: "失败",
    failureReasons: "确定性失败原因",
    forbiddenHitsFailure: "检测到禁止的自我暴露内容",
    memoryUnchangedFailure: "Human 记忆未发生变化",
    missingFactsFailure: "缺少预期事实",
    expectedFactsFailure: "预期事实检查未通过",
    deterministicFailureFallback: "至少一项确定性检查失败，请展开下方评估详情。",
    agentId: "智能体 ID",
    archived: "已归档",
    purged: "已清理",
    finalMemoryLayers: "最终记忆层",
    noMemoryLayers: "未记录最终记忆层。",
    memoryLimit: "上限",
    emptyMemory: "（空）",
    initialHumanMemory: "初始 Human 记忆",
    finalHumanMemory: "最终 Human 记忆",
    assessmentDetails: "评估详情",
    deterministicScore: "确定性评分",
    judge: "辅助评审",
    turnEvidence: "逐轮对话证据",
    turn: "第",
    userInput: "用户输入",
    assistantReplies: "助手回复",
    noAssistantReply: "未记录助手回复。",
    humanMemoryBefore: "更新前 Human 记忆",
    humanMemoryAfter: "更新后 Human 记忆",
    memoryChanged: "记忆已变更",
    memoryDelta: "Human 记忆差异",
    addedMemoryLines: "新增内容",
    removedMemoryLines: "移除内容",
    noMemoryDelta: "未记录逐行记忆变化。",
    toolCalls: "全部工具调用",
    noToolCalls: "未记录工具调用。",
    memoryToolCalls: "记忆工具调用",
    noMemoryToolCalls: "未记录记忆工具调用。",
    rawDiagnostics: "原始运行诊断",
    rawDiagnosticsIntro: "产物和输出尾部仍可用于底层排障。",
    serverDefault: "服务端默认值",
    runsTitle: "运行记录",
    selectRun: "选择运行",
    refreshSelectedRun: "刷新当前运行",
    cancelRun: "取消运行",
    artifactsTitle: "产物",
    refreshArtifacts: "刷新产物",
    noArtifacts: "暂无产物。",
    yes: "是",
    no: "否",
    open: "打开",
    activeArtifact: "当前产物",
    noActiveArtifact: "无",
    artifactContentPlaceholder: "产物内容显示在此。",
    outputTail: "运行输出尾部",
    statusTitle: "状态",
    errorTitle: "错误",
    createdRun: "已创建运行",
    cancelRequested: "已请求取消",
    selectRunPlaceholder: "请选择运行",
    id: "ID",
    type: "类型",
    exists: "存在",
    action: "操作",
  },
} as const;

export type TestCenterCopy = {
  [Key in keyof (typeof COPY)["en"]]: string;
};

export const BEHAVIOR_EVALUATION_RUN_TYPES = [
  "chat_memory_eval",
] as const satisfies readonly TestRunType[];

export const OPERATIONAL_RUN_TYPES = [
  "ade_api_e2e_check",
  "ade_mvp_smoke_e2e_check",
  "agent_runtime_v3_acceptance",
] as const satisfies readonly TestRunType[];

export const TEST_RUN_TYPES: readonly TestRunType[] = [
  ...BEHAVIOR_EVALUATION_RUN_TYPES,
  ...OPERATIONAL_RUN_TYPES,
];

export function getTestCenterCopy(locale: Locale): TestCenterCopy {
  return COPY[locale];
}

export function getTestRunTypeLabel(copy: TestCenterCopy, runType: TestRunType): string {
  switch (runType) {
    case "chat_memory_eval":
      return copy.chatMemoryEvaluationRun;
    case "ade_api_e2e_check":
      return copy.adeApiE2eCheckRun;
    case "ade_mvp_smoke_e2e_check":
      return copy.adeMvpSmokeCheckRun;
    case "agent_runtime_v3_acceptance":
      return copy.nativeRuntimeQualificationRun;
  }
}
