import type { TestRunType } from "./api";
import type { Locale } from "@/shared/i18n";

const COPY = {
  en: {
    kicker: "MVP Module",
    title: "Test Center",
    createRunTitle: "Create Test Run",
    runType: "Run type",
    model: "Model",
    prompt: "Prompt",
    persona: "Persona",
    embedding: "Embedding",
    fixture: "Fixture",
    rounds: "Rounds",
    timeoutSeconds: "Timeout (seconds)",
    retryCount: "Retry Count",
    judgeEnabled: "Advisory LLM judge",
    submitting: "Submitting...",
    createRun: "Create Run",
    refreshRuns: "Refresh Runs",
    runsTitle: "Runs",
    selectRun: "Select run",
    refreshSelectedRun: "Refresh Selected Run",
    cancelRun: "Cancel Run",
    artifactsTitle: "Artifacts",
    refreshArtifacts: "Refresh Artifacts",
    noArtifacts: "No artifacts discovered yet.",
    yes: "yes",
    no: "no",
    open: "Open",
    activeArtifact: "Active artifact",
    noActiveArtifact: "none",
    artifactContentPlaceholder: "Artifact content appears here.",
    outputTail: "Run Output Tail",
    statusTitle: "Status",
    errorTitle: "Error",
    createdRun: "Created run",
    cancelRequested: "Cancel requested for",
    selectRunPlaceholder: "Select run",
    id: "ID",
    type: "Type",
    exists: "Exists",
    action: "Action",
  },
  zh: {
    kicker: "MVP 模块",
    title: "测试中心",
    createRunTitle: "创建测试运行",
    runType: "运行类型",
    model: "模型",
    prompt: "提示词",
    persona: "人设",
    embedding: "Embedding",
    fixture: "对话样本",
    rounds: "轮数",
    timeoutSeconds: "超时（秒）",
    retryCount: "重试次数",
    judgeEnabled: "启用辅助 LLM 评审",
    submitting: "提交中...",
    createRun: "创建运行",
    refreshRuns: "刷新运行列表",
    runsTitle: "运行记录",
    selectRun: "选择运行",
    refreshSelectedRun: "刷新当前运行",
    cancelRun: "取消运行",
    artifactsTitle: "产物",
    refreshArtifacts: "刷新产物",
    noArtifacts: "暂无产物。",
    yes: "是",
    no: "否",
    open: "打开",
    activeArtifact: "当前产物",
    noActiveArtifact: "无",
    artifactContentPlaceholder: "产物内容显示在此。",
    outputTail: "运行输出尾部",
    statusTitle: "状态",
    errorTitle: "错误",
    createdRun: "已创建运行",
    cancelRequested: "已请求取消",
    selectRunPlaceholder: "请选择运行",
    id: "ID",
    type: "类型",
    exists: "存在",
    action: "操作",
  },
} as const;

export type TestCenterCopy = {
  [Key in keyof (typeof COPY)["en"]]: string;
};

export const TEST_RUN_TYPES: TestRunType[] = [
  "ade_api_e2e_check",
  "ade_mvp_smoke_e2e_check",
  "chat_memory_eval",
];

export function getTestCenterCopy(locale: Locale): TestCenterCopy {
  return COPY[locale];
}
