"""
Auto-generated by ADE Prompt Center.
"""

LABEL = "Label Football Entities V1"
DESCRIPTION = "Football article extraction example for player and team lists."
OUTPUT_SCHEMA = "{\"type\":\"object\",\"properties\":{\"players\":{\"type\":\"array\",\"maxItems\":64,\"items\":{\"type\":\"string\",\"minLength\":1}},\"teams\":{\"type\":\"array\",\"maxItems\":64,\"items\":{\"type\":\"string\",\"minLength\":1}}},\"required\":[\"players\",\"teams\"],\"additionalProperties\":false}"
PROMPT = """Extract football player names into players and club or team names into teams. Return JSON only."""
