"""
Auto-generated by ADE Prompt Center.
"""

LABEL = "Label Generic Entities V1"
DESCRIPTION = "Generic extraction baseline that returns grouped entity lists in JSON."
OUTPUT_SCHEMA = "{\"type\":\"object\",\"properties\":{\"people\":{\"type\":\"array\",\"maxItems\":64,\"items\":{\"type\":\"string\",\"minLength\":1}},\"organizations\":{\"type\":\"array\",\"maxItems\":64,\"items\":{\"type\":\"string\",\"minLength\":1}},\"locations\":{\"type\":\"array\",\"maxItems\":64,\"items\":{\"type\":\"string\",\"minLength\":1}},\"dates\":{\"type\":\"array\",\"maxItems\":64,\"items\":{\"type\":\"string\",\"minLength\":1}},\"events\":{\"type\":\"array\",\"maxItems\":64,\"items\":{\"type\":\"string\",\"minLength\":1}}},\"required\":[\"people\",\"organizations\",\"locations\",\"dates\",\"events\"],\"additionalProperties\":false}"
PROMPT = """Extract people, organizations, locations, dates, and events from the article. Return JSON only."""
