export const COMMENT_LAB_COPY = {
  en: {
    kicker: "Stateless Module",
    title: "Comment Lab",
    intro:
      "Generate one-shot comments with independent prompt/persona/model controls. This route stays stateless and supports three explicit task-shape strategies.",
    tuningTitle: "Tuning Settings",
    mainContentTitle: "Content Workspace",
    innerWorksTitle: "Inner Works",
    defaultsFromEnv: "Defaults are loaded from runtime environment and can be overridden per request.",
    model: "Model",
    selectModel: "Select model",
    prompt: "Prompt",
    persona: "Persona",
    maxTokens: "Max Tokens",
    maxTokensHint: "Set 0 for no max token limit.",
    timeoutSeconds: "Timeout (seconds)",
    retryCount: "Retry Count",
    retryCountHint: "Set 0 to disable retries. Maximum 5.",
    taskShape: "Task Shape",
    taskShapeClassic: "Classic (persona in user)",
    taskShapeAllInSystem: "All in system",
    taskShapeStructuredOutput: "Structured output (JSON)",
    cachePrompt: "Use prompt cache",
    cachePromptHint: "Off by default for fair persona comparisons on llama-server.",
    enableThinking: "Enable thinking",
    enableThinkingHint: "For supported vLLM/Gemma models only; slower but exposes separated reasoning.",
    temperature: "Temperature",
    topP: "Top P",
    topK: "Top K",
    userInput: "Input Text",
    userInputPlaceholder: "Paste a news summary, a thread excerpt, or your own draft context here...",
    generate: "Generate Comment",
    generating: "Generating...",
    refreshOptions: "Refresh Options",
    optionsRefreshed: "Commenting options refreshed.",
    outputTitle: "Generated Comment",
    outputPlaceholder: "Generated content will appear here.",
    provider: "Provider",
    modelUsed: "Model Used",
    maxTokensUsed: "Max Tokens Used",
    timeoutUsed: "Timeout Used",
    taskShapeUsed: "Task Shape Used",
    cachePromptUsed: "Prompt Cache Used",
    enableThinkingUsed: "Thinking Used",
    temperatureUsed: "Temperature Used",
    topPUsed: "Top P Used",
    topKUsed: "Top K Used",
    runtimeMetaTitle: "Runtime",
    timingMetaTitle: "Timing",
    tokenMetaTitle: "Token Usage",
    responseSeconds: "Response Time (s)",
    usagePromptTokens: "Prompt Tokens",
    usageCompletionTokens: "Completion Tokens",
    usageTotalTokens: "Total Tokens",
    usageReasoningTokens: "Reasoning Tokens",
    receivedAt: "Response Received At",
    selectedAttempt: "Selected Attempt",
    finishReason: "Finish Reason",
    rawRequestTitle: "Raw Request",
    rawRequestPlaceholder: "Raw provider request JSON will appear here.",
    rawReplyTitle: "Raw Model Reply",
    rawReplyPlaceholder: "Raw provider response JSON will appear here.",
    popOutCard: "Pop Out Card",
    closeCard: "Close",
    readableView: "Readable View",
    rawJsonView: "Raw JSON",
    notesTitle: "Execution Notes",
    notesOne: "This route is stateless and does not create or modify Letta agent state.",
    notesTwo: "No embedding model is required for this commenting flow.",
    notesThree: "Provider requests are sent through an OpenAI-compatible chat completions endpoint.",
    notesFour: "Structured output shape requests JSON and extracts the comment field.",
    selectRequired: "Please choose model, prompt, and persona before generating.",
    inputRequired: "Input text is required.",
    invalidMaxTokens: "Max tokens must be a non-negative integer (0 means no limit).",
    invalidTimeout: "Timeout must be a positive number.",
    invalidRetryCount: "Retry count must be an integer between 0 and 5.",
    invalidTemperature: "Temperature must be between 0 and 2.",
    invalidTopP: "Top P must be greater than 0 and at most 1.",
    invalidTopK: "Top K must be a positive integer, or blank to use the model default.",
    loadingError: "Failed to load commenting options",
    generateError: "Comment generation failed",
  },
  zh: {
    kicker: "无状态模块",
    title: "评论实验室",
    intro: "以独立模型、Prompt、Persona 控制进行单次评论生成。该页面保持无状态，并支持三种明确的任务形状策略。",
    tuningTitle: "参数调优",
    mainContentTitle: "内容工作区",
    innerWorksTitle: "内部信息",
    defaultsFromEnv: "默认值来自运行环境，可在每次请求中覆盖。",
    model: "模型",
    selectModel: "选择模型",
    prompt: "Prompt",
    persona: "Persona",
    maxTokens: "最大 Token",
    maxTokensHint: "设置为 0 表示不限制最大 Token。",
    timeoutSeconds: "超时时间（秒）",
    retryCount: "重试次数",
    retryCountHint: "设置为 0 表示禁用重试，最大为 5。",
    taskShape: "任务形状",
    taskShapeClassic: "经典模式（persona 放在 user）",
    taskShapeAllInSystem: "全部放在 system",
    taskShapeStructuredOutput: "结构化输出（JSON）",
    cachePrompt: "使用 Prompt 缓存",
    cachePromptHint: "默认关闭，便于在 llama-server 上公平比较 Persona。",
    enableThinking: "启用 Thinking",
    enableThinkingHint: "仅支持部分 vLLM/Gemma 模型；速度更慢，但会返回分离的 reasoning。",
    temperature: "Temperature",
    topP: "Top P",
    topK: "Top K",
    userInput: "输入文本",
    userInputPlaceholder: "粘贴新闻摘要、评论串内容，或你的草稿上下文...",
    generate: "生成评论",
    generating: "生成中...",
    refreshOptions: "刷新配置",
    optionsRefreshed: "评论配置已刷新。",
    outputTitle: "生成结果",
    outputPlaceholder: "生成内容会显示在这里。",
    provider: "Provider",
    modelUsed: "使用模型",
    maxTokensUsed: "实际最大 Token",
    timeoutUsed: "实际超时",
    taskShapeUsed: "实际任务形状",
    cachePromptUsed: "实际 Prompt 缓存",
    enableThinkingUsed: "实际 Thinking",
    temperatureUsed: "实际 Temperature",
    topPUsed: "实际 Top P",
    topKUsed: "实际 Top K",
    runtimeMetaTitle: "运行参数",
    timingMetaTitle: "时序",
    tokenMetaTitle: "Token 使用",
    responseSeconds: "响应耗时（秒）",
    usagePromptTokens: "输入 Token",
    usageCompletionTokens: "输出 Token",
    usageTotalTokens: "总 Token",
    usageReasoningTokens: "推理 Token",
    receivedAt: "响应接收时间",
    selectedAttempt: "命中尝试",
    finishReason: "完成原因",
    rawRequestTitle: "原始请求",
    rawRequestPlaceholder: "这里会显示发送给 provider 的原始请求 JSON。",
    rawReplyTitle: "模型原始回复",
    rawReplyPlaceholder: "这里会显示 provider 返回的原始 JSON。",
    popOutCard: "弹出卡片",
    closeCard: "关闭",
    readableView: "可读视图",
    rawJsonView: "原始 JSON",
    notesTitle: "执行说明",
    notesOne: "该路径为无状态，不会创建或修改 Letta 智能体状态。",
    notesTwo: "该评论流程不需要 embedding 模型。",
    notesThree: "请求通过 OpenAI 兼容的 chat completions 接口发送。",
    notesFour: "结构化输出模式会请求 JSON，并提取其中的 comment 字段。",
    selectRequired: "生成前请先选择模型、Prompt 与 Persona。",
    inputRequired: "请输入文本。",
    invalidMaxTokens: "最大 Token 必须是非负整数（0 表示不限制）。",
    invalidTimeout: "超时时间必须是正数。",
    invalidRetryCount: "重试次数必须是 0 到 5 之间的整数。",
    invalidTemperature: "Temperature 必须在 0 到 2 之间。",
    invalidTopP: "Top P 必须大于 0 且不超过 1。",
    invalidTopK: "Top K 必须是正整数，或留空使用模型默认值。",
    loadingError: "加载评论配置失败",
    generateError: "评论生成失败",
  },
} as const;
